# Generated by Django 4.0.1 on 2022-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Hairdresser'), (3, 'Administrator')], default=1, verbose_name='role'),
        ),
    ]
