# Generated by Django 4.0.1 on 2022-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('nameHairdresser', models.CharField(max_length=100, verbose_name='Hairdresser')),
                ('treatment', models.SmallIntegerField(choices=[(1, 'Hair cut'), (2, 'Dye hair')], default=1)),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.SmallIntegerField(choices=[(1, '13:00 - 14:00'), (2, '14:00 - 15:00'), (3, '15:00 - 16:00'), (4, '16:00 - 17:00'), (5, '17:00 - 18:00')], verbose_name='Time')),
                ('complete', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Complete')], default=1)),
            ],
        ),
    ]
