# Generated by Django 4.0.1 on 2022-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betakroll', '0002_remove_booking_namehairdresser_booking_hairdresser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='complete',
            field=models.SmallIntegerField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default=('ACTIVE', 'Active')),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.SmallIntegerField(choices=[('ONE', '13:00 - 14:00'), ('TWO', '14:00 - 15:00'), ('THREE', '15:00 - 16:00'), ('FOUR', '16:00 - 17:00'), ('FIVE', '17:00 - 18:00')], verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='treatment',
            field=models.SmallIntegerField(choices=[('HAIRCUT', 'Hair cut'), ('DYEHAIR', 'Dye hair')]),
        ),
    ]
