# Generated by Django 4.0.1 on 2022-05-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betakroll', '0002_remove_booking_namehairdresser_booking_hairdresser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
