# Generated by Django 4.0.1 on 2022-05-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betakroll', '0003_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Date'),
        ),
    ]
