# Generated by Django 4.0.1 on 2022-05-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betakroll', '0003_alter_booking_complete_alter_booking_time_and_more'),
        ('betakroll', '0004_alter_booking_date'),
    ]

    operations = [
    ]
