# Generated by Django 4.0.1 on 2022-05-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betakroll', '0005_merge_20220523_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='complete',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Complete')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.SmallIntegerField(choices=[(1, '13:00 - 14:00'), (2, '14:00 - 15:00'), (3, '15:00 - 16:00'), (4, '16:00 - 17:00'), (5, '17:00 - 18:00')], verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='treatment',
            field=models.SmallIntegerField(choices=[(1, 'Hair cut'), (2, 'Dye hair')]),
        ),
    ]
